name: Deploy Server to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies and run tests
      run: |
        npm ci
        npm test || echo "No tests found, skipping..."
        
    - name: Build Docker image
      run: |
        docker build -t cinemahint:latest .
        
    - name: Debug SSH Connection
      run: |
        echo "Testing SSH connection to ${{ secrets.EC2_HOST }}"
        echo "Using username: ${{ secrets.EC2_USERNAME }}"
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT || 22 }}
        debug: true
        script: |
          set -e  # Exit on any error
          
          echo "🏠 Current directory: $(pwd)"
          echo "👤 Current user: $(whoami)"
          
          # Check if deployment directory exists
          echo "🔍 Checking deployment directory..."
          if [ ! -d "/home/${{ secrets.EC2_USERNAME }}/cinema-hint-server" ]; then
            echo "❌ Directory /home/${{ secrets.EC2_USERNAME }}/cinema-hint-server does not exist!"
            echo "📁 Available directories in /home/${{ secrets.EC2_USERNAME }}:"
            ls -la /home/${{ secrets.EC2_USERNAME }}/
            exit 1
          fi
          
          # Navigate to deployment directory
          echo "📂 Navigating to deployment directory..."
          cd /home/${{ secrets.EC2_USERNAME }}/cinema-hint-server
          
          echo "📍 Now in: $(pwd)"
          echo "📋 Directory contents:"
          ls -la
          
          # Check if it's a git repository
          if [ ! -d ".git" ]; then
            echo "❌ This is not a git repository!"
            exit 1
          fi
          
          echo "🔗 Git remote configuration:"
          git remote -v
          
          echo "🔄 Current git status:"
          git status
          
          # Check if there are local changes
          if ! git diff --quiet || ! git diff --cached --quiet; then
            echo "⚠️ Local changes detected, stashing them..."
            git stash push -m "Auto-stash before deployment $(date)"
          fi
          
          # Add untracked files that might interfere
          echo "📦 Adding untracked files to .gitignore if needed..."
          echo "backups/" >> .gitignore
          echo "nginx/ssl/" >> .gitignore
          echo "*.log" >> .gitignore
          
          # Remove any problematic config files that should be deleted
          echo "🧹 Cleaning up deleted config files..."
          rm -f nginx/conf.d/scale.conf nginx/conf.d/locations.conf
          
          echo "📥 Pulling latest code..."
          git pull origin main || {
            echo "❌ Git pull failed!"
            echo "🔍 Git status after failed pull:"
            git status
            echo "🔍 Git log to see what's happening:"
            git log --oneline -5
            exit 1
          }
          
          echo "✅ Latest commits after pull:"
          git log --oneline -3
          
          # Create backup of current deployment
          timestamp=$(date +%Y%m%d_%H%M%S)
          mkdir -p backups
          docker-compose logs > backups/app_logs_$timestamp.log
          
          # Stop current services with force and remove volumes
          echo "🛑 Stopping all services..."
          docker-compose down --remove-orphans
          
          # Force stop any remaining containers
          echo "🔄 Force stopping any remaining containers..."
          docker stop $(docker ps -q --filter "name=cinemahint") 2>/dev/null || true
          docker rm $(docker ps -aq --filter "name=cinemahint") 2>/dev/null || true
          
          # Build new image
          echo "🏗️ Building new Docker image..."
          docker build -t cinemahint:latest . --no-cache
          
          # Clean up old images and containers
          echo "🧹 Cleaning up old Docker resources..."
          docker image prune -f
          docker container prune -f
          docker volume prune -f
          
          # Start services with production profile
          echo "🚀 Starting services..."
          docker-compose --profile production up -d
          
          # Wait a bit for containers to start
          sleep 10
          
          # Restart nginx specifically to ensure it picks up any changes
          echo "🔄 Restarting nginx container..."
          docker-compose restart nginx
          
          # Wait for services to be healthy
          echo "⏳ Waiting for services to start..."
          sleep 30
          
          # Clear Redis cache to ensure fresh state after deployment
          echo "🧹 Clearing Redis cache for fresh deployment state..."
          docker exec cinemahint-redis redis-cli FLUSHALL || echo "⚠️ Redis cache clear failed, continuing..."
          
          # Check individual service status
          echo "📊 Service status:"
          docker-compose ps
          
          # Check for failed containers
          FAILED_CONTAINERS=$(docker ps -a --filter "status=restarting" --filter "status=exited" --format "{{.Names}}")
          if [ ! -z "$FAILED_CONTAINERS" ]; then
            echo "❌ Failed containers detected: $FAILED_CONTAINERS"
            echo "📋 Logs for failed containers:"
            for container in $FAILED_CONTAINERS; do
              echo "--- Logs for $container ---"
              docker logs --tail=20 $container
            done
          fi
          
          # Health check (try both local and external)
          echo "🧪 Testing application health..."
          if curl -f http://localhost:5000/api/health; then
            echo "✅ Internal health check passed!"
          else
            echo "❌ Internal health check failed!"
            echo "📋 App container logs:"
            docker logs --tail=20 cinemahint-app
          fi
          
          # Test external access (if nginx is working)
          if curl -f https://cinemahint.adilhusain.me/api/health 2>/dev/null; then
            echo "✅ External HTTPS access working!"
          else
            echo "⚠️ External HTTPS access failed (might be nginx issue)"
            if docker ps --filter "name=cinemahint-nginx" --filter "status=running" | grep -q nginx; then
              echo "📋 Nginx container logs:"
              docker logs --tail=20 cinemahint-nginx
            else
              echo "❌ Nginx container is not running!"
            fi
          fi
          
          # Show status
          docker-compose ps
          
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT || 22 }}
        script: |
          # Additional health checks
          echo "🔍 Running deployment verification..."
          
          # Check if all services are running
          cd /home/${{ secrets.EC2_USERNAME }}/cinema-hint-server
          
          if docker-compose ps | grep -q "Up.*healthy"; then
            echo "✅ All services are healthy"
          else
            echo "⚠️ Some services may not be healthy:"
            docker-compose ps
          fi
          
          # Test API endpoints
          echo "🧪 Testing API endpoints..."
          
          # Health endpoint
          if curl -f https://cinemahint.adilhusain.me/api/health; then
            echo "✅ Health endpoint working"
          else
            echo "❌ Health endpoint failed"
          fi
          
          # Check Redis connection
          if docker exec cinemahint-redis redis-cli ping | grep -q "PONG"; then
            echo "✅ Redis is responding"
          else
            echo "❌ Redis connection failed"
          fi
          
          echo "🎉 Deployment verification completed!"
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🎉 Deployment to https://cinemahint.adilhusain.me was successful!"
        else
          echo "❌ Deployment failed. Check the logs above for details."
          exit 1
        fi