name: Deploy Server to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies and run tests
      run: |
        npm ci
        npm test || echo "No tests found, skipping..."
        
    - name: Build Docker image
      run: |
        docker build -t cinemahint:latest .
        
    - name: Debug SSH Connection
      run: |
        echo "Testing SSH connection to ${{ secrets.EC2_HOST }}"
        echo "Using username: ${{ secrets.EC2_USERNAME }}"
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT || 22 }}
        debug: true
        script: |
          set -e  # Exit on any error
          
          echo "🏠 Current directory: $(pwd)"
          echo "👤 Current user: $(whoami)"
          
          # Check if deployment directory exists
          echo "🔍 Checking deployment directory..."
          if [ ! -d "/home/${{ secrets.EC2_USERNAME }}/cinema-hint-server" ]; then
            echo "❌ Directory /home/${{ secrets.EC2_USERNAME }}/cinema-hint-server does not exist!"
            echo "📁 Available directories in /home/${{ secrets.EC2_USERNAME }}:"
            ls -la /home/${{ secrets.EC2_USERNAME }}/
            exit 1
          fi
          
          # Navigate to deployment directory
          echo "📂 Navigating to deployment directory..."
          cd /home/${{ secrets.EC2_USERNAME }}/cinema-hint-server
          
          echo "📍 Now in: $(pwd)"
          echo "📋 Directory contents:"
          ls -la
          
          # Check if it's a git repository
          if [ ! -d ".git" ]; then
            echo "❌ This is not a git repository!"
            exit 1
          fi
          
          echo "🔗 Git remote configuration:"
          git remote -v
          
          echo "🔄 Current git status:"
          git status
          
          # Check if there are local changes
          if ! git diff --quiet || ! git diff --cached --quiet; then
            echo "⚠️ Local changes detected, stashing them..."
            git stash push -m "Auto-stash before deployment $(date)"
          fi
          
          # Add untracked files that might interfere
          echo "📦 Adding untracked files to .gitignore if needed..."
          echo "backups/" >> .gitignore
          echo "nginx/ssl/" >> .gitignore
          echo "*.log" >> .gitignore
          
          echo "📥 Pulling latest code..."
          git pull origin main || {
            echo "❌ Git pull failed!"
            echo "🔍 Git status after failed pull:"
            git status
            echo "🔍 Git log to see what's happening:"
            git log --oneline -5
            exit 1
          }
          
          echo "✅ Latest commits after pull:"
          git log --oneline -3
          
          # Create backup of current deployment
          timestamp=$(date +%Y%m%d_%H%M%S)
          mkdir -p backups
          docker-compose logs > backups/app_logs_$timestamp.log
          
          # Stop current services
          docker-compose down
          
          # Build new image
          docker build -t cinemahint:latest .
          
          # Clean up old images and containers
          docker image prune -f
          docker container prune -f
          
          # Start services with production profile
          docker-compose --profile production up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to start..."
          sleep 30
          
          # Health check
          if curl -f http://localhost:5000/api/health; then
            echo "✅ Deployment successful! Application is healthy."
          else
            echo "❌ Health check failed. Check logs:"
            docker-compose logs --tail=50
            exit 1
          fi
          
          # Show status
          docker-compose ps
          
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT || 22 }}
        script: |
          # Additional health checks
          echo "🔍 Running deployment verification..."
          
          # Check if all services are running
          cd /home/${{ secrets.EC2_USERNAME }}/cinema-hint-server
          
          if docker-compose ps | grep -q "Up.*healthy"; then
            echo "✅ All services are healthy"
          else
            echo "⚠️ Some services may not be healthy:"
            docker-compose ps
          fi
          
          # Test API endpoints
          echo "🧪 Testing API endpoints..."
          
          # Health endpoint
          if curl -f https://cinemahint.adilhusain.me/api/health; then
            echo "✅ Health endpoint working"
          else
            echo "❌ Health endpoint failed"
          fi
          
          # Check Redis connection
          if docker exec cinemahint-redis redis-cli ping | grep -q "PONG"; then
            echo "✅ Redis is responding"
          else
            echo "❌ Redis connection failed"
          fi
          
          echo "🎉 Deployment verification completed!"
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🎉 Deployment to https://cinemahint.adilhusain.me was successful!"
        else
          echo "❌ Deployment failed. Check the logs above for details."
          exit 1
        fi